configs:
  global:
    LINKS_PORT: # default: 5000 ----- notice: this port only used, when you want run this project in normal mode. in docker the container port is 80.
    LINKS_HOST: # default: '127.0.0.1' ----- notice: this port only used, when you want run this project in normal mode. in docker the container port is 80.
    LINKS_DEBUG_MODE: # on => enable / off => disable | default off
    LINKS_BASIC_AUTH: # on => enable / off => disable | default off
    LINKS_TITLE: Links # base tile of page
    LINKS_ADMIN_PASS: # default password for username admin 'LinksAdminPass'

targets:
  - group: 'git'
    color_tag: "pink" # color of bubbles you can set color code or name like CSS (#008000 or green)
    text_color: "black" # color of bubbles you can set color code or name like CSS (#40354e or green)
    urls:
      - url: http://github.com
        title: Github
      - url: http://gitlab.com
        title: Gitlab
  - group: 'DevOps'
    color_tag: "#7b4f4f"
    text_color: "#fff"
    urls:
      - url: http://docker.com
        title: Docker
      - url: https://stackoverflow.com/
        title: Stackoverflow
      - url: https://ubuntu.com/
        title: Ubuntu
  - group: 'other'
    color_tag: "#312626"
    text_color: "#e65396"
    urls:
      - url: http://other.com
        title: Other
      - url: http:example.com/
        title: Example
