targets:
  - group: 'monitoring'
    urls:
      - url:
        href: http://google.com
        title:  Google
      - url:
        href: http://yahoo.com
        title: Yahoo
      - url:
        href: http://time.ir
        title: Time
      - url:
        href: http://gitlab.com
        title: Gitlab


  - group: 'logging'
    urls:
      - url:
        href: http://docker.com
        title:  Docker
      - url:
        href: http://git.ir
        title:  GitIr
      - url:
        href: http://bbc.com
        title:  BBC
      - url:
        href: http://gitlab.com
        title: Gitlab
      - url:
        href: http://github.com
        title: Github


  - group: 'other'
    urls:
      - url:
        href: http://other.com
        title:  Other
      - url:
        href: http:example.com/
        title: Example

configs:
  global:
    LINKS_PORT: 8002 # default: 5000
    LINKS_HOST: 127.0.0.1 # default: '127.0.0.1'
    LINKS_DEBUG_MODE: off # on => enable / off => disable | default False
    BASIC_AUTH: off # on => enable / off => disable | default False
    HTPASS_FILE_ADDRESS: ./pass_file
    admin_pass: alid
