configs:
  global:
    LINKS_PORT: # default: 5000
    LINKS_HOST: # default: '127.0.0.1'
    LINKS_DEBUG_MODE: # on => enable / off => disable | default off
    LINKS_BASIC_AUTH: # on => enable / off => disable | default off
    LINKS_HTPASS_FILE_ADDRESS: # default is htpasswd.pass
    LINKS_ADMIN_PASS: # default password for username admin 'LinksAdminPass' 

targets:
  - group: 'monitoring'
    urls:
      - url:
        href: http://google.com
        title:  Google
      - url:
        href: http://gitlab.com
        title: Gitlab
  - group: 'logging'
    urls:
      - url:
        href: http://docker.com
        title:  Docker
      - url:
        href: http://git.ir
        title:  GitIr
      - url:
        href: http://github.com
        title: Github
  - group: 'other'
    urls:
      - url:
        href: http://other.com
        title:  Other
      - url:
        href: http:example.com/
        title: Example

